# this docker-compose for k8s remote environment
version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: remote_k8s.Dockerfile
    image: 74th/vscode-typescript-handson:latest
    volumes:
      - /home/nnyn/Documents/vscode-typescript-hanson/environment/manifests/template/settings.yaml:/root/settings/settings.yaml
      - /home/nnyn/Documents/vscode-typescript-hanson/tasks.py:/root/tasks.py
      - /home/nnyn/Documents/vscode-typescript-hanson/tmp/volume:/home/ubuntu
    ports:
      - 22
