apiVersion: apps/v1
kind: Deployment
metadata:
  name: typescript-handson
spec:
  selector:
    matchLabels:
      app: n1
  template:
    metadata:
      labels:
        app: n1
---

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-port
spec:
  type: LoadBalancer
  selector:
    app: n1
